global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8001"]
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8002"]
  - job_name: "catalog-service"
    static_configs:
      - targets: ["catalog-service:8003"]
  - job_name: "cart-service"
    static_configs:
      - targets: ["cart-service:8004"]
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8005"]
  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8006"]
  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8007"]
  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8008"]
